export default {
  home: '/',
  login: '/api/auth/login',
  logout: '/api/auth/logout',
  signUp: '/api/auth/signup',
  tournaments: '/tournaments',
  marketplace: '/marketplace',
  howToPlay: '/howtoplay',
  help: 'https://google.com',
  winners: 'https://google.com',
  partner: 'https://google.com',
  contact: 'https://google.com',
  privacy: 'https://google.com',
  terms: 'https://google.com',
};
